<a href="https://colab.research.google.com/github/Isudipsubedi/data-science/blob/main/1Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
arr.ndim

1

In [7]:
#1D tensor is also a vector
#The dimension of the vector is 4, as it contains 4 values.

2D tensor/matrices

In [13]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
mat


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
mat.ndim

2

**ND Tensor**

In [14]:
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
mat2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
ND = np.array(([mat1,mat2,mat2],[mat1,mat2,mat2],[mat1,mat2,mat2]))

In [17]:
ND


array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [18]:
ND.ndim

4

In [20]:
#Machine Learning 0-5D

**RANK, AXES, SHAPE**