<a href="https://colab.research.google.com/github/Isudipsubedi/data-science/blob/main/1Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr.ndim

1

In [ ]:
#1D tensor is also a vector
#The dimension of the vector is 4, as it contains 4 values.

2D tensor/matrices

In [ ]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
mat


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mat.ndim

2

**ND Tensor**

In [ ]:
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
mat2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
ND = np.array(([mat1,mat2,mat2],[mat1,mat2,mat2],[mat1,mat2,mat2]))

In [ ]:
ND


array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [ ]:
ND.ndim

4

In [ ]:
#Machine Learning 0-5D

**RANK, AXES, SHAPE**

In [1]:
# NO. of axix = Rank = No. of aim

**Example of 1D Tensor**

In [5]:
#lets say we have dataset of student with 4 columns cgpa | iq | state | placement
#students(10000)
#let ktm = 1 and non ktm = 0
#[3.5,92,0] = 1D Tensor = 3D vector

**Example of 2D Tensor**

**Example of 3D Tensor**

In [7]:
#usecase in NLP
# Hi | Shova | Sudipa | Nabaraj
# 1      0       0         0

In [ ]:
# Hi Shova
# Hi Sudipa
# Hi Nabaraj

# [1,0,0,0][0,1,0,0]
# [1,0,0,0][0,0,1,0]
# [1,0,0,0][0,0,0,1]

[
 [[1,0,0,0],[0,1,0,0]]
 [[1,0,0,0],[0,0,1,0]]
 [[1,0,0,0],[0,0,0,1]]
]

Rank = 3
No. of items = 3 * 2 * 4

**Timeseries Data**

In [ ]:
# stock's highest & lowest price during the day for 365 days
# (365, 2) 2D tensor

        Highest    Lowest
    D1  ------     ------
    D1  ------     ------
    D1  ------     ------
    D1  ------     ------    
    D1  ------     ------
    D1  ------     ------    
    D1  ------     ------
    D1  ------     ------
    

What if 10 years : 3D tensor

```
# This is formatted as code
```



In [9]:
10 * 365 * 2

7300

**Example 4D Tensor : Computer vision**




**Example 5D Tensor : Videos**